// Code generated by tygo. DO NOT EDIT.
// Source: internal/core/types.go

export type Status = "proposed" | "decided" | "out_of_scope" | "superseded";

export type Priority = "assumption" | "low" | "medium" | "high" | "critical";

export type RelationshipType =
  | "blocks"
  | "influences"
  | "supersedes"
  | "relates_to";

export type ActorKind = "human" | "agent";

export type Action =
  | "create"
  | "update"
  | "delete"
  | "decide"
  | "undecide"
  | "scope_out"
  | "supersede"
  | "relate"
  | "unrelate"
  | "rename"
  | "restore"
  | "external_edit"
  | "external_create"
  | "external_delete"
  | "tree_create"
  | "tree_delete"
  | "tree_rename"
  | "tree_archive"
  | "actor_add"
  | "actor_rename"
  | "actor_archive"
  | "config_change"
  | "schema_migrate";

export type Kind =
  | "decision"
  | "tree"
  | "actor"
  | "relationship"
  | "config";

export interface Relationship {
  type: RelationshipType;
  target: string;
  note?: string;
}

export interface Decision {
  id: string;
  slug?: string;
  schema_version: number;
  tree: string;
  summary: string;
  priority: Priority;
  status: Status;
  creator: string;
  assignee?: string;
  tags?: string[];
  recommended_summary?: string;
  recommended_full?: string;
  recommended_by?: string;
  actual_choice?: string;
  actual_choice_reason?: string;
  decided_by?: string[];
  is_recommended: boolean;
  out_of_scope_reason?: string;
  decision_full_description?: string;
  relationships?: Relationship[];
  _rev?: string;
  decided_at?: string;
  created_at: string;
  updated_at: string;
  description?: string;
}

export interface Tree {
  slug: string;
  schema_version: number;
  title?: string;
  name?: string;
  description?: string;
  archived: boolean;
  created_at: string;
  updated_at: string;
  layout?: {
    direction?: string;
  };
}

export interface Actor {
  handle: string;
  display_name: string;
  name?: string;
  email?: string;
  kind: ActorKind;
  active: boolean;
  archived: boolean;
}

export interface EventPayload {
  before?: Record<string, unknown>;
  after?: Record<string, unknown>;
  [key: string]: unknown;
}

export interface Event {
  event_id: string;
  v: number;
  ts: string;
  actor: string;
  action: Action;
  kind: Kind;
  tree?: string;
  id: string;
  payload: EventPayload;
}

// API response wrappers

export interface PaginatedResponse<T> {
  items: T[];
  next_cursor?: string;
}

export interface TreesResponse {
  trees: Tree[];
}

export interface ActorsResponse {
  actors: Actor[];
}

export interface AuditResponse {
  items: Event[];
  next_cursor?: string;
}

export interface Metrics {
  total_decisions: number;
  by_status: Record<Status, number>;
  by_priority: Record<Priority, number>;
  by_creator: Array<{ handle: string; count: number }>;
  assumptions_count: number;
  unblocked_proposed_count: number;
  oldest_proposed_id?: string;
}

export interface HealthResponse {
  version: string;
  status: "ok";
}

export interface StateResponse {
  as_of: string;
  decisions: Decision[];
}

export interface QueueItem {
  id: string;
  summary: string;
  blocking_count?: number;
}

export interface SpearheadResponse {
  items: QueueItem[];
}

export interface QuickWinsResponse {
  items: Decision[];
}

export interface UnassignedResponse {
  items: Decision[];
}

// Problem Details (RFC 7807)
export interface ProblemDetails {
  type: string;
  title: string;
  status: number;
  detail: string;
  instance?: string;
}
